image: git.gittos.net:5050/tgittos/gittos.net/runner-base

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  MATOMO_IMAGE: $CI_REGISTRY_IMAGE/mp-matomo:$CI_COMMIT_SHORT_SHA
  PROMETHEUS_IMAGE: $CI_REGISTRY_IMAGE/mp-prometheus:$CI_COMMIT_SHORT_SHA
  PLATFORM_IMAGE: $CI_REGISTRY_IMAGE/money-printer:$CI_COMMIT_SHORT_SHA
  MATOMO_TAGGED_IMAGE: $CI_REGISTRY_IMAGE/mp-matomo:$CI_COMMIT_TAG
  PROMETHEUS_TAGGED_IMAGE: $CI_REGISTRY_IMAGE/mp-prometheus:$CI_COMMIT_TAG
  PLATFORM_TAGGED_IMAGE: $CI_REGISTRY_IMAGE/money-printer:$CI_COMMIT_TAG
  MATOMO_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/mp-matomo:latest
  PROMETHEUS_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/mp-prometheus:latest
  PLATFORM_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/money-printer:latest

services:
  - docker:dind

before_script:
  - |
    docker version
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build
  - release

build:
  stage: build
  script:
    - |
      docker-compose build
      docker tag mp-matomo $MATOMO_IMAGE
      docker push $MATOMO_IMAGE
      docker tag mp-prometheus $PROMETHEUS_IMAGE
      docker push $PROMETHEUS_IMAGE
      docker tag money-printer $PLATFORM_IMAGE
      docker push $PLATFORM_IMAGE
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
  
release:
  stage: release
  script:
    - |
      docker pull $MATOMO_IMAGE
      docker tag $MATOMO_IMAGE $MATOMO_RELEASE_IMAGE
      docker push $MATOMO_RELEASE_IMAGE
      docker pull $PROMETHEUS_IMAGE
      docker tag $PROMETHEUS_IMAGE $PROMETHEUS_RELEASE_IMAGE
      docker push $PROMETHEUS_RELEASE_IMAGE
      docker pull $PLATFORM_IMAGE
      docker tag $PLATFORM_IMAGE $PLATFORM_RELEASE_IMAGE
      docker push $PLATFORM_RELEASE_IMAGE
      if [ $CI_COMMIT_TAG ]; then
        docker tag $PROMETHEUS_IMAGE $PROMETHEUS_TAGGED_IMAGE
        docker push $PROMETHEUS_TAGGED_IMAGE
        docker tag $MATOMO_IMAGE $MATOMO_TAGGED_IMAGE
        docker push $MATOMO_TAGGED_IMAGE
        docker tag $PLATFORM_IMAGE $PLATFORM_TAGGED_IMAGE
        docker push $PLATFORM_TAGGED_IMAGE
      fi;
  rules:
    # always release if the commit was tagged
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_NAME == "main"'
      when: always
    # allow manual releasing from the main branch
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_REF_NAME == "main"'
      when: manual
      allow_failure: true
