image: git.gittos.net:5050/tgittos/gittos.net/runner-base

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  MATOMO_IMAGE: $CI_REGISTRY_IMAGE/mp-matomo
  MATOMO_TAGGED_IMAGE: $CI_REGISTRY_IMAGE/mp-matomo:$CI_COMMIT_TAG
  PROMETHEUS_IMAGE: $CI_REGISTRY_IMAGE/mp-prometheus
  PROMETHEUS_TAGGED_IMAGE: $CI_REGISTRY_IMAGE/mp-prometheus:$CI_COMMIT_TAG
  PLATFORM_IMAGE: $CI_REGISTRY_IMAGE/money-printer
  PLATFORM_TAGGED_IMAGE: $CI_REGISTRY_IMAGE/money-printer:$CI_COMMIT_TAG
  RPROXY_IMAGE: $CI_REGISTRY_IMAGE/money-printer
  RPROXY_TAGGED_IMAGE: $CI_REGISTRY_IMAGE/money-printer:$CI_COMMIT_TAG

services:
  - docker:dind

before_script:
  - |
    docker version
    docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build
  - release

build:
  stage: build
  script:
    - |
      docker-compose build
      docker push $MATOMO_IMAGE
      docker push $PROMETHEUS_IMAGE
      docker push $PLATFORM_IMAGE
      docker push $RPROXY_IMAGE
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
  
release:
  stage: release
  script:
    - |
      docker pull $PROMETHEUS_IMAGE
      docker tag $PROMETHEUS_IMAGE $PROMETHEUS_TAGGED_IMAGE
      docker push $PROMETHEUS_TAGGED_IMAGE
      docker pull $MATOMO_IMAGE
      docker tag $MATOMO_IMAGE $MATOMO_TAGGED_IMAGE
      docker push $MATOMO_TAGGED_IMAGE
      docker pull $PLATFORM_IMAGE
      docker tag $PLATFORM_IMAGE $PLATFORM_TAGGED_IMAGE
      docker push $PLATFORM_TAGGED_IMAGE
      docker pull $RPROXY_IMAGE
      docker tag $RPROXY_IMAGE $RPROXY_TAGGED_IMAGE
      docker push $RPROXY_TAGGED_IMAGE
  rules:
    # always release if the commit was tagged
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_REF_NAME == "main"'
      when: always
    # allow manual releasing from the main branch
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_REF_NAME == "main"'
      when: manual
      allow_failure: true
