services:
  matomo:
    build:
      dockerfile: Dockerfile
      context: ./docker/matomo
    # volumes:
    #   - matomo-db-data:/var/lib/mysql
    ports:
      - 80:80
      - 443:443
    entrypoint: [ "/bin/sh", "/init-matomo.sh" ]
    image: mp-matomo

  prometheus:
    build:
      dockerfile: Dockerfile
      context: ./docker/prometheus
    # volumes:
    #   - prometheus-db-data:/var/lib/mysql
    ports:
      - 80:80
      - 443:443
    image: mp-prometheus
