services:
  matomo:
    build:
      dockerfile: Dockerfile
      context: ./docker/matomo
    volumes:
      - matomo-config:/var/www/matomo/config
    image: mp-matomo

  prometheus:
    build:
      dockerfile: Dockerfile
      context: ./docker/prometheus
    image: mp-prometheus

  platform:
    build:
      dockerfile: Dockerfile
      context: ./docker/platform
    image: money-printer

volumes:
  matomo-config: null
