services:
  matomo:
    build:
      dockerfile: Dockerfile
      context: ./docker/matomo
    volumes:
      - matomo-config:/var/www/matomo/config
    image: git.gittos.net:5050/money-printer/money-printer-infrastructure/mp-matomo

  prometheus:
    build:
      dockerfile: Dockerfile
      context: ./docker/prometheus
    image: git.gittos.net:5050/money-printer/money-printer-infrastructure/mp-prometheus
  hasura:
    build:
      dockerfile: Dockerfile
      context: ./docker/hasura
    image: git.gittos.net:5050/money-printer/money-printer-infrastructure/mp-hasura

  platform:
    build:
      dockerfile: Dockerfile
      context: ./docker/platform
    image: git.gittos.net:5050/money-printer/money-printer-infrastructure/money-printer
  
  rproxy:
    build:
      dockerfile: Dockerfile
      context: ./docker/rproxy
    image: git.gittos.net:5050/money-printer/money-printer-infrastructure/mp-rproxy
    volumes:
      - ./templates:/etc/nginx/templates

volumes:
  matomo-config: null
