services:
  gitlab-docker-runner:
    container_name: gitlab-docker-runner
    restart: always
    privileged: true
    image: gitlab/gitlab-runner
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock