services:
  gitlab-runner:
    container_name: gitlab-runner
    restart: always
    image: gitlab/gitlab-runner
    volumes:
      - ./gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock